name: Android APK CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/lib/android-sdk
      ANDROID_HOME: /usr/lib/android-sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Install required system dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Download Android command line tools
        run: |
          sudo mkdir -p ${ANDROID_SDK_ROOT}
          cd /tmp
          wget -O android-commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
          sudo unzip -qo android-commandlinetools.zip -d ${ANDROID_SDK_ROOT}

      - name: Install Android SDK packages
        run: |
          yes | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses
          sudo ${ANDROID_SDK_ROOT}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --update
          yes | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-35" "build-tools;35.0.0" "platform-tools"
          sudo chown -R $USER:${USER} ${ANDROID_SDK_ROOT}

      - name: Build APK
        run: ./mvnw -B -Dandroid.sdk.location=${ANDROID_SDK_ROOT} -Dandroid.platform=35 clean package

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: uqureader-apk
          path: target/*.apk
